steps:
- name: 'gcr.io/k8s-skaffold/pack'
  args:
  - build
  - --builder=gcr.io/buildpacks/builder:v1 # Use a general purpose buildpack
  - --trust-builder # Only if the buildpack is on your trusted list
  - --path=.
  - --tag=gcr.io/$PROJECT_ID/interactive-fire-calculator:latest # Replace with your image name
images:
- gcr.io/$PROJECT_ID/interactive-fire-calculator:latest # Replace with your image name
