import {afterEach,it,expect,vi} from 'vitest';
import {act} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {VehicleCalculator} from './VehicleCalculator';
import {seoCalculators} from './lib/seoCalculators';
import type {AuthState} from './auth';
import type {CalculatorSavedResult,CalculatorSaveRequest} from './CalculatorLibrary';
// @ts-expect-error React test environment flag
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
let root:Root,container:HTMLDivElement;
afterEach(()=>{if(root)act(()=>root.unmount());container?.remove();});
const auth:AuthState={provider:'clerk',status:'signed-in',isConfigured:true,isSignedIn:true,getToken:async()=> 'synthetic',user:{id:'synthetic',email:'synthetic@example.invalid',displayName:'Synthetic'}};
const save=vi.fn(async(_r:CalculatorSaveRequest)=>({destinationRoute:'/plans' as const,message:'Saved',savedResultId:'synthetic'}));
async function render(history:CalculatorSavedResult[]=[]){save.mockClear();container=document.createElement('div');document.body.appendChild(container);root=createRoot(container);await act(async()=>root.render(<VehicleCalculator auth={auth} calculator={seoCalculators.find(c=>c.slug==='lease-vs-buy')!} onSaveResult={save} savedResults={history}/>));}
async function click(name:string){const b=[...container.querySelectorAll('button')].find(b=>b.textContent===name);expect(b,name).toBeDefined();await act(async()=>b!.click());}
async function fill(key:string,value:string){const i=container.querySelector<HTMLInputElement>(`#vehicle-${key}`)!;expect(i).not.toBeNull();await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(i,value);i.dispatchEvent(new Event('input',{bubbles:true}));});}
it('starts required resale/terms empty; explicit example reconciles chart and table',async()=>{await render();expect(container.querySelector<HTMLInputElement>('#vehicle-resale')?.value).toBe('');expect(container.querySelector('.calculator-result-metric-primary')).toBeNull();await click('Use example terms');expect(container.querySelector('.calculator-result-metric-primary')?.textContent).toContain('$2,600');expect(container.textContent).toContain('$11,000');expect(container.textContent).toContain('$8,400');expect(save).not.toHaveBeenCalled();await click('Save comparison');expect(save.mock.calls[0][0].result.modelVersion).toBe('vehicle-cost-v1');expect(save.mock.calls[0][0].values.resale).toBe(14000);});
it('preserves incomplete input and blocks beyond-quote comparisons until explicit continuation',async()=>{await render();await click('Use example terms');await fill('years','3');expect(container.querySelector('.calculator-result-metric-primary')).toBeNull();const check=container.querySelector<HTMLInputElement>('#vehicle-extendLease')!;await act(async()=>check.click());await fill('extensionMonthly','350');expect(container.querySelector('.calculator-result-metric-primary')).not.toBeNull();await fill('resale','-');expect(container.querySelector<HTMLInputElement>('#vehicle-resale')?.value).toBe('-');expect(container.querySelector('.calculator-result-metric-primary')).toBeNull();expect([...container.querySelectorAll('button')].find(b=>b.textContent==='Save comparison')?.disabled).toBe(true);await fill('resale','0');expect(container.querySelector('.calculator-result-metric-primary')).not.toBeNull();});
it('preserves legacy snapshot; restore requires missing resale and lease period explicitly',async()=>{const old:CalculatorSavedResult={id:'old',calculatorSlug:'lease-vs-buy',calculatorTitle:'Lease vs Buy Calculator',currency:'USD',createdAt:'2026-09-01',inputValues:{homePrice:35000,downPayment:5000,rate:7,loanYears:5,years:4,rent:450},result:{narrative:'Earlier monthly comparison',metrics:[{label:'Monthly cost to buy',value:594,valueType:'currency'}]}};const bytes=JSON.stringify(old);await render([old]);expect(container.textContent).toContain('Earlier approximation');expect(container.textContent).toContain('$594');await click('Load saved inputs');expect(container.querySelector<HTMLInputElement>('#vehicle-resale')?.value).toBe('');expect(container.querySelector<HTMLInputElement>('#vehicle-leaseYears')?.value).toBe('');expect(container.querySelector('.calculator-result-metric-primary')).toBeNull();expect(save).not.toHaveBeenCalled();expect(JSON.stringify(old)).toBe(bytes);});
